spring.application.name=communicate

spring.ai.dashscope.api-key=${Ali_API_KEY}
spring.ai.dashscope.chat.options.model=qwen-max
spring.ai.dash-scope.embedding.options.model=text-embedding-v2
spring.ai.dash-scope.image.options.model=wanx-v1
spring.ai.dash-scope.audio.api-key=${Ali_API_KEY}
spring.ai.dash-scope.audio.options.model=sambert-zhixiang-v1
spring.ai.dash-scope.audio.realtime.model=gummy-realtime-v1

server.port=8080

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

python.script.tts.path=scripts/tts.py

# application.properties
spring.datasource.url=jdbc:mysql://rm-bp1cfwt1ik59yi3my.mysql.rds.aliyuncs.com:3306/light_translate?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=guangge
spring.datasource.password=Dl_wxg_8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect