spring.application.name=communicate

spring.ai.dashscope.api-key=
spring.ai.dashscope.chat.options.model=qwen-turbo
spring.ai.dash-scope.embedding.options.model=text-embedding-v2
spring.ai.dash-scope.image.options.model=wanx-v1
spring.ai.dash-scope.audio.api-key=
spring.ai.dash-scope.audio.options.model=sambert-zhixiang-v1
spring.ai.dash-scope.audio.realtime.model=gummy-realtime-v1
spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}

spring.ai.baidu.app-id=${Baidu_APP_ID}
spring.ai.baidu.api-key=${Baidu_API_KEY}
spring.ai.wechat.app-id=${WECHAT_APP_ID}
spring.ai.wechat.api-secret=${WECHAT_API_SECRET}

spring.ai.baidu.ocr.api-key=${Baidu_OCR_API_KEY}
spring.ai.baidu.ocr.api-secret=${Baidu_OCR_API_SECRET}
spring.ai.baidu.ocr.url=https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic

aliyun.oss.endpoint=oss-cn-hangzhou.aliyuncs.com
aliyun.oss.accessKeyId=LTAI5tD6QTNqSxghj3iBWtHT
aliyun.oss.accessKeySecret=poUVGzhrwxBZs0A00ecCmMGpMxowOZ
aliyun.oss.bucketName=light-translate
aliyun.oss.fileHost=audio/

server.port=8080

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

python.script.tts.path=/app/scripts/tts.py
python.script.image.path=scripts/generate_image.py

# application.properties
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.web.socket.max-binary-message-size= 10485760

server.ssl.key-store = classpath:5aicv.cn.jks
server.ssl.key-store-password = k7knveob
server.ssl.keyStoreType = JKS

logging.level.root=info
logging.level.com.light.translate=debug
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n